### ISSUE TITLE
个人问题

### ISSUE THREAD

**Issue by wushenak** [28598519a/CounterSideDecryptor#1]
大佬，工具解密完文件都是在dec那个文件夹里吗？怎么才能看到效果，我以为把解密好的文件再用assetstudio提取一遍就行了，但是好像不对，不解密assetstudio根本识别不出asset文件，直接读取解密完的dec文件夹现实的是读取文件出现错误。叨扰了，如果嫌我我太烦了也就不用回了，我自己再琢磨

**Comment by 28598519a** [comment]
抱歉很少看信箱，所以這麼晚才回

你是不是沒用最新的AssetStudio開?

我隨便試了一個是可以的
![](https://user-images.githubusercontent.com/33422418/229331215-5054b78d-293c-45d6-8596-e8f7073de2e7.png)

**Comment by wushenak** [comment]
谢谢大佬解答，我目前出门电脑不在身边，我回去再试试，打扰了。
