### ISSUE TITLE
有償求助。

### ISSUE THREAD

**Issue by LxXStudio2025** [28598519a/CounterSideDecryptor#2]
你好我想問下你這邊能否獲取到《刀劍神域：關鍵鬥士》（Saoif）的數據包，如果可以請聯繫我電子郵件156848450@qq.com
我會給予報酬！非常感謝！！！

**Comment by 28598519a** [comment]
對刀劍沒啥興趣，抱歉了哈

**Comment by LxXStudio2025** [comment]
額，有空看看唄？這個遊戲找了很久都沒什麼人研究，但是他的數據包非常的多，而且是熱更新。一直都沒辦法拿齊全，太難頂了。我很想拿到它裡面的模型，單位質量都挺高的
&nbsp;


I&#39;M&nbsp;The&nbsp;LxX
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午4:17
收件人: ***@***.***&gt;; 
抄送: "I&apos;M The ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [28598519a/CounterSideDecryptor] 有償求助。 (Issue #2)





 
对刀剑没啥兴趣，抱歉了哈
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您创作了线程。Message ID: ***@***.***&gt;
