### ISSUE TITLE
Echocalypse

### ISSUE THREAD

**Issue by YoxalLoyal** [28598519a/CounterSideDecryptor#6]
Hello. Are you familiar with the game Echocalypse? I was hoping if you could help me decrypt the image files from the game? I provide you with sample files to work with.
https://mega.nz/folder/eioGBSZY#2x-4Io9ht3_DQ-jSyBTiaA

![Screenshot 2023-10-03 204749](https://github.com/28598519a/CounterSideDecryptor/assets/34036620/1889cc81-f295-42f9-be7b-20945efc8aee)
![Screenshot 2023-10-03 204802](https://github.com/28598519a/CounterSideDecryptor/assets/34036620/0259dabe-bb0b-4f82-8796-f46c741745d1)

**Comment by 28598519a** [comment]
[echocalypse.zip](https://github.com/28598519a/CounterSideDecryptor/files/13168845/echocalypse.zip)

Not sure if this work, try this, untested.
